import type { Question } from "./api";

// Comprehensive list of LeetCode questions
export const leetcodeQuestions: Question[] = [
  {
    id: 1,
    title: "Two Sum",
    difficulty: "Easy",
    tags: ["Array", "Hash Table"],
    leetcode_id: "1",
  },
  {
    id: 2,
    title: "Add Two Numbers",
    difficulty: "Medium",
    tags: ["Linked List", "Math", "Recursion"],
    leetcode_id: "2",
  },
  {
    id: 3,
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    tags: ["Hash Table", "String", "Sliding Window"],
    leetcode_id: "3",
  },
  {
    id: 4,
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    tags: ["Array", "Binary Search", "Divide and Conquer"],
    leetcode_id: "4",
  },
  {
    id: 5,
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    tags: ["String", "Dynamic Programming"],
    leetcode_id: "5",
  },
  {
    id: 6,
    title: "Zigzag Conversion",
    difficulty: "Medium",
    tags: ["String"],
    leetcode_id: "6",
  },
  {
    id: 7,
    title: "Reverse Integer",
    difficulty: "Medium",
    tags: ["Math"],
    leetcode_id: "7",
  },
  {
    id: 8,
    title: "String to Integer (atoi)",
    difficulty: "Medium",
    tags: ["String"],
    leetcode_id: "8",
  },
  {
    id: 9,
    title: "Palindrome Number",
    difficulty: "Easy",
    tags: ["Math"],
    leetcode_id: "9",
  },
  {
    id: 10,
    title: "Regular Expression Matching",
    difficulty: "Hard",
    tags: ["String", "Dynamic Programming", "Recursion"],
    leetcode_id: "10",
  },
  {
    id: 11,
    title: "Container With Most Water",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Greedy"],
    leetcode_id: "11",
  },
  {
    id: 12,
    title: "Integer to Roman",
    difficulty: "Medium",
    tags: ["Hash Table", "Math", "String"],
    leetcode_id: "12",
  },
  {
    id: 13,
    title: "Roman to Integer",
    difficulty: "Easy",
    tags: ["Hash Table", "Math", "String"],
    leetcode_id: "13",
  },
  {
    id: 14,
    title: "Longest Common Prefix",
    difficulty: "Easy",
    tags: ["String"],
    leetcode_id: "14",
  },
  {
    id: 15,
    title: "3Sum",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Sorting"],
    leetcode_id: "15",
  },
  {
    id: 16,
    title: "3Sum Closest",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Sorting"],
    leetcode_id: "16",
  },
  {
    id: 17,
    title: "Letter Combinations of a Phone Number",
    difficulty: "Medium",
    tags: ["Hash Table", "String", "Backtracking"],
    leetcode_id: "17",
  },
  {
    id: 18,
    title: "4Sum",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Sorting"],
    leetcode_id: "18",
  },
  {
    id: 19,
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    tags: ["Linked List", "Two Pointers"],
    leetcode_id: "19",
  },
  {
    id: 20,
    title: "Valid Parentheses",
    difficulty: "Easy",
    tags: ["String", "Stack"],
    leetcode_id: "20",
  },
  {
    id: 21,
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    tags: ["Linked List", "Recursion"],
    leetcode_id: "21",
  },
  {
    id: 22,
    title: "Generate Parentheses",
    difficulty: "Medium",
    tags: ["String", "Dynamic Programming", "Backtracking"],
    leetcode_id: "22",
  },
  {
    id: 23,
    title: "Merge k Sorted Lists",
    difficulty: "Hard",
    tags: [
      "Linked List",
      "Divide and Conquer",
      "Heap (Priority Queue)",
      "Merge Sort",
    ],
    leetcode_id: "23",
  },
  {
    id: 24,
    title: "Swap Nodes in Pairs",
    difficulty: "Medium",
    tags: ["Linked List", "Recursion"],
    leetcode_id: "24",
  },
  {
    id: 25,
    title: "Reverse Nodes in k-Group",
    difficulty: "Hard",
    tags: ["Linked List", "Recursion"],
    leetcode_id: "25",
  },
  {
    id: 26,
    title: "Remove Duplicates from Sorted Array",
    difficulty: "Easy",
    tags: ["Array", "Two Pointers"],
    leetcode_id: "26",
  },
  {
    id: 27,
    title: "Remove Element",
    difficulty: "Easy",
    tags: ["Array", "Two Pointers"],
    leetcode_id: "27",
  },
  {
    id: 28,
    title: "Find the Index of the First Occurrence in a String",
    difficulty: "Easy",
    tags: ["Two Pointers", "String", "String Matching"],
    leetcode_id: "28",
  },
  {
    id: 29,
    title: "Divide Two Integers",
    difficulty: "Medium",
    tags: ["Math", "Bit Manipulation"],
    leetcode_id: "29",
  },
  {
    id: 30,
    title: "Substring with Concatenation of All Words",
    difficulty: "Hard",
    tags: ["Hash Table", "String", "Sliding Window"],
    leetcode_id: "30",
  },
  {
    id: 31,
    title: "Next Permutation",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers"],
    leetcode_id: "31",
  },
  {
    id: 32,
    title: "Longest Valid Parentheses",
    difficulty: "Hard",
    tags: ["String", "Dynamic Programming", "Stack"],
    leetcode_id: "32",
  },
  {
    id: 33,
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    tags: ["Array", "Binary Search"],
    leetcode_id: "33",
  },
  {
    id: 34,
    title: "Find First and Last Position of Element in Sorted Array",
    difficulty: "Medium",
    tags: ["Array", "Binary Search"],
    leetcode_id: "34",
  },
  {
    id: 35,
    title: "Search Insert Position",
    difficulty: "Easy",
    tags: ["Array", "Binary Search"],
    leetcode_id: "35",
  },
  {
    id: 36,
    title: "Valid Sudoku",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "Matrix"],
    leetcode_id: "36",
  },
  {
    id: 37,
    title: "Sudoku Solver",
    difficulty: "Hard",
    tags: ["Array", "Backtracking", "Matrix"],
    leetcode_id: "37",
  },
  {
    id: 38,
    title: "Count and Say",
    difficulty: "Medium",
    tags: ["String"],
    leetcode_id: "38",
  },
  {
    id: 39,
    title: "Combination Sum",
    difficulty: "Medium",
    tags: ["Array", "Backtracking"],
    leetcode_id: "39",
  },
  {
    id: 40,
    title: "Combination Sum II",
    difficulty: "Medium",
    tags: ["Array", "Backtracking"],
    leetcode_id: "40",
  },
  {
    id: 41,
    title: "First Missing Positive",
    difficulty: "Hard",
    tags: ["Array", "Hash Table"],
    leetcode_id: "41",
  },
  {
    id: 42,
    title: "Trapping Rain Water",
    difficulty: "Hard",
    tags: [
      "Array",
      "Two Pointers",
      "Dynamic Programming",
      "Stack",
      "Monotonic Stack",
    ],
    leetcode_id: "42",
  },
  {
    id: 43,
    title: "Multiply Strings",
    difficulty: "Medium",
    tags: ["Math", "String", "Simulation"],
    leetcode_id: "43",
  },
  {
    id: 44,
    title: "Wildcard Matching",
    difficulty: "Hard",
    tags: ["String", "Dynamic Programming", "Greedy", "Recursion"],
    leetcode_id: "44",
  },
  {
    id: 45,
    title: "Jump Game II",
    difficulty: "Medium",
    tags: ["Array", "Dynamic Programming", "Greedy"],
    leetcode_id: "45",
  },
  {
    id: 46,
    title: "Permutations",
    difficulty: "Medium",
    tags: ["Array", "Backtracking"],
    leetcode_id: "46",
  },
  {
    id: 47,
    title: "Permutations II",
    difficulty: "Medium",
    tags: ["Array", "Backtracking"],
    leetcode_id: "47",
  },
  {
    id: 48,
    title: "Rotate Image",
    difficulty: "Medium",
    tags: ["Array", "Math", "Matrix"],
    leetcode_id: "48",
  },
  {
    id: 49,
    title: "Group Anagrams",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "String", "Sorting"],
    leetcode_id: "49",
  },
  {
    id: 50,
    title: "Pow(x, n)",
    difficulty: "Medium",
    tags: ["Math", "Recursion"],
    leetcode_id: "50",
  },
  {
    id: 51,
    title: "N-Queens",
    difficulty: "Hard",
    tags: ["Array", "Backtracking"],
    leetcode_id: "51",
  },
  {
    id: 52,
    title: "N-Queens II",
    difficulty: "Hard",
    tags: ["Backtracking"],
    leetcode_id: "52",
  },
  {
    id: 53,
    title: "Maximum Subarray",
    difficulty: "Medium",
    tags: ["Array", "Divide and Conquer", "Dynamic Programming"],
    leetcode_id: "53",
  },
  {
    id: 54,
    title: "Spiral Matrix",
    difficulty: "Medium",
    tags: ["Array", "Matrix", "Simulation"],
    leetcode_id: "54",
  },
  {
    id: 55,
    title: "Jump Game",
    difficulty: "Medium",
    tags: ["Array", "Dynamic Programming", "Greedy"],
    leetcode_id: "55",
  },
  {
    id: 56,
    title: "Merge Intervals",
    difficulty: "Medium",
    tags: ["Array", "Sorting"],
    leetcode_id: "56",
  },
  {
    id: 57,
    title: "Insert Interval",
    difficulty: "Medium",
    tags: ["Array"],
    leetcode_id: "57",
  },
  {
    id: 58,
    title: "Length of Last Word",
    difficulty: "Easy",
    tags: ["String"],
    leetcode_id: "58",
  },
  {
    id: 59,
    title: "Spiral Matrix II",
    difficulty: "Medium",
    tags: ["Array", "Matrix", "Simulation"],
    leetcode_id: "59",
  },
  {
    id: 60,
    title: "Permutation Sequence",
    difficulty: "Hard",
    tags: ["Math", "Recursion"],
    leetcode_id: "60",
  },
  {
    id: 61,
    title: "Rotate List",
    difficulty: "Medium",
    tags: ["Linked List", "Two Pointers"],
    leetcode_id: "61",
  },
  {
    id: 62,
    title: "Unique Paths",
    difficulty: "Medium",
    tags: ["Math", "Dynamic Programming", "Combinatorics"],
    leetcode_id: "62",
  },
  {
    id: 63,
    title: "Unique Paths II",
    difficulty: "Medium",
    tags: ["Array", "Dynamic Programming", "Matrix"],
    leetcode_id: "63",
  },
  {
    id: 64,
    title: "Minimum Path Sum",
    difficulty: "Medium",
    tags: ["Array", "Dynamic Programming", "Matrix"],
    leetcode_id: "64",
  },
  {
    id: 65,
    title: "Valid Number",
    difficulty: "Hard",
    tags: ["String"],
    leetcode_id: "65",
  },
  {
    id: 66,
    title: "Plus One",
    difficulty: "Easy",
    tags: ["Array", "Math"],
    leetcode_id: "66",
  },
  {
    id: 67,
    title: "Add Binary",
    difficulty: "Easy",
    tags: ["Math", "String", "Bit Manipulation", "Simulation"],
    leetcode_id: "67",
  },
  {
    id: 68,
    title: "Text Justification",
    difficulty: "Hard",
    tags: ["String", "Simulation"],
    leetcode_id: "68",
  },
  {
    id: 69,
    title: "Sqrt(x)",
    difficulty: "Easy",
    tags: ["Math", "Binary Search"],
    leetcode_id: "69",
  },
  {
    id: 70,
    title: "Climbing Stairs",
    difficulty: "Easy",
    tags: ["Math", "Dynamic Programming", "Memoization"],
    leetcode_id: "70",
  },
  {
    id: 71,
    title: "Simplify Path",
    difficulty: "Medium",
    tags: ["String", "Stack"],
    leetcode_id: "71",
  },
  {
    id: 72,
    title: "Edit Distance",
    difficulty: "Hard",
    tags: ["String", "Dynamic Programming"],
    leetcode_id: "72",
  },
  {
    id: 73,
    title: "Set Matrix Zeroes",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "Matrix"],
    leetcode_id: "73",
  },
  {
    id: 74,
    title: "Search a 2D Matrix",
    difficulty: "Medium",
    tags: ["Array", "Binary Search", "Matrix"],
    leetcode_id: "74",
  },
  {
    id: 75,
    title: "Sort Colors",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Sorting"],
    leetcode_id: "75",
  },
  {
    id: 76,
    title: "Minimum Window Substring",
    difficulty: "Hard",
    tags: ["Hash Table", "String", "Sliding Window"],
    leetcode_id: "76",
  },
  {
    id: 77,
    title: "Combinations",
    difficulty: "Medium",
    tags: ["Backtracking"],
    leetcode_id: "77",
  },
  {
    id: 78,
    title: "Subsets",
    difficulty: "Medium",
    tags: ["Array", "Backtracking", "Bit Manipulation"],
    leetcode_id: "78",
  },
  {
    id: 79,
    title: "Word Search",
    difficulty: "Medium",
    tags: ["Array", "Backtracking", "Matrix"],
    leetcode_id: "79",
  },
  {
    id: 80,
    title: "Remove Duplicates from Sorted Array II",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers"],
    leetcode_id: "80",
  },
  {
    id: 81,
    title: "Search in Rotated Sorted Array II",
    difficulty: "Medium",
    tags: ["Array", "Binary Search"],
    leetcode_id: "81",
  },
  {
    id: 82,
    title: "Remove Duplicates from Sorted List II",
    difficulty: "Medium",
    tags: ["Linked List", "Two Pointers"],
    leetcode_id: "82",
  },
  {
    id: 83,
    title: "Remove Duplicates from Sorted List",
    difficulty: "Easy",
    tags: ["Linked List"],
    leetcode_id: "83",
  },
  {
    id: 84,
    title: "Largest Rectangle in Histogram",
    difficulty: "Hard",
    tags: ["Array", "Stack", "Monotonic Stack"],
    leetcode_id: "84",
  },
  {
    id: 85,
    title: "Maximal Rectangle",
    difficulty: "Hard",
    tags: [
      "Array",
      "Dynamic Programming",
      "Stack",
      "Matrix",
      "Monotonic Stack",
    ],
    leetcode_id: "85",
  },
  {
    id: 86,
    title: "Partition List",
    difficulty: "Medium",
    tags: ["Linked List", "Two Pointers"],
    leetcode_id: "86",
  },
  {
    id: 87,
    title: "Scramble String",
    difficulty: "Hard",
    tags: ["String", "Dynamic Programming"],
    leetcode_id: "87",
  },
  {
    id: 88,
    title: "Merge Sorted Array",
    difficulty: "Easy",
    tags: ["Array", "Two Pointers", "Sorting"],
    leetcode_id: "88",
  },
  {
    id: 89,
    title: "Gray Code",
    difficulty: "Medium",
    tags: ["Math", "Backtracking", "Bit Manipulation"],
    leetcode_id: "89",
  },
  {
    id: 90,
    title: "Subsets II",
    difficulty: "Medium",
    tags: ["Array", "Backtracking", "Bit Manipulation"],
    leetcode_id: "90",
  },
  {
    id: 91,
    title: "Decode Ways",
    difficulty: "Medium",
    tags: ["String", "Dynamic Programming"],
    leetcode_id: "91",
  },
  {
    id: 92,
    title: "Reverse Linked List II",
    difficulty: "Medium",
    tags: ["Linked List"],
    leetcode_id: "92",
  },
  {
    id: 93,
    title: "Restore IP Addresses",
    difficulty: "Medium",
    tags: ["String", "Backtracking"],
    leetcode_id: "93",
  },
  {
    id: 94,
    title: "Binary Tree Inorder Traversal",
    difficulty: "Easy",
    tags: ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "94",
  },
  {
    id: 95,
    title: "Unique Binary Search Trees II",
    difficulty: "Medium",
    tags: [
      "Dynamic Programming",
      "Backtracking",
      "Tree",
      "Binary Search Tree",
      "Binary Tree",
    ],
    leetcode_id: "95",
  },
  {
    id: 96,
    title: "Unique Binary Search Trees",
    difficulty: "Medium",
    tags: [
      "Math",
      "Dynamic Programming",
      "Tree",
      "Binary Search Tree",
      "Binary Tree",
    ],
    leetcode_id: "96",
  },
  {
    id: 97,
    title: "Interleaving String",
    difficulty: "Medium",
    tags: ["String", "Dynamic Programming"],
    leetcode_id: "97",
  },
  {
    id: 98,
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    leetcode_id: "98",
  },
  {
    id: 99,
    title: "Recover Binary Search Tree",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    leetcode_id: "99",
  },
  {
    id: 100,
    title: "Same Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "100",
  },
  {
    id: 101,
    title: "Symmetric Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "101",
  },
  {
    id: 102,
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    tags: ["Tree", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "102",
  },
  {
    id: 103,
    title: "Binary Tree Zigzag Level Order Traversal",
    difficulty: "Medium",
    tags: ["Tree", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "103",
  },
  {
    id: 104,
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "104",
  },
  {
    id: 105,
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "Divide and Conquer", "Tree", "Binary Tree"],
    leetcode_id: "105",
  },
  {
    id: 106,
    title: "Construct Binary Tree from Inorder and Postorder Traversal",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "Divide and Conquer", "Tree", "Binary Tree"],
    leetcode_id: "106",
  },
  {
    id: 107,
    title: "Binary Tree Level Order Traversal II",
    difficulty: "Medium",
    tags: ["Tree", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "107",
  },
  {
    id: 108,
    title: "Convert Sorted Array to Binary Search Tree",
    difficulty: "Easy",
    tags: [
      "Array",
      "Divide and Conquer",
      "Tree",
      "Binary Search Tree",
      "Binary Tree",
    ],
    leetcode_id: "108",
  },
  {
    id: 109,
    title: "Convert Sorted List to Binary Search Tree",
    difficulty: "Medium",
    tags: [
      "Linked List",
      "Divide and Conquer",
      "Tree",
      "Binary Search Tree",
      "Binary Tree",
    ],
    leetcode_id: "109",
  },
  {
    id: 110,
    title: "Balanced Binary Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "110",
  },
  {
    id: 111,
    title: "Minimum Depth of Binary Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "111",
  },
  {
    id: 112,
    title: "Path Sum",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "112",
  },
  {
    id: 113,
    title: "Path Sum II",
    difficulty: "Medium",
    tags: ["Backtracking", "Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "113",
  },
  {
    id: 114,
    title: "Flatten Binary Tree to Linked List",
    difficulty: "Medium",
    tags: ["Linked List", "Stack", "Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "114",
  },
  {
    id: 115,
    title: "Distinct Subsequences",
    difficulty: "Hard",
    tags: ["String", "Dynamic Programming"],
    leetcode_id: "115",
  },
  {
    id: 116,
    title: "Populating Next Right Pointers in Each Node",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "116",
  },
  {
    id: 117,
    title: "Populating Next Right Pointers in Each Node II",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "117",
  },
  {
    id: 118,
    title: "Pascal's Triangle",
    difficulty: "Easy",
    tags: ["Array", "Dynamic Programming"],
    leetcode_id: "118",
  },
  {
    id: 119,
    title: "Pascal's Triangle II",
    difficulty: "Easy",
    tags: ["Array", "Dynamic Programming"],
    leetcode_id: "119",
  },
  {
    id: 120,
    title: "Triangle",
    difficulty: "Medium",
    tags: ["Array", "Dynamic Programming"],
    leetcode_id: "120",
  },
  {
    id: 121,
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    tags: ["Array", "Dynamic Programming"],
    leetcode_id: "121",
  },
  {
    id: 122,
    title: "Best Time to Buy and Sell Stock II",
    difficulty: "Medium",
    tags: ["Array", "Dynamic Programming", "Greedy"],
    leetcode_id: "122",
  },
  {
    id: 123,
    title: "Best Time to Buy and Sell Stock III",
    difficulty: "Hard",
    tags: ["Array", "Dynamic Programming"],
    leetcode_id: "123",
  },
  {
    id: 124,
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    tags: ["Dynamic Programming", "Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "124",
  },
  {
    id: 125,
    title: "Valid Palindrome",
    difficulty: "Easy",
    tags: ["Two Pointers", "String"],
    leetcode_id: "125",
  },
  {
    id: 126,
    title: "Word Ladder II",
    difficulty: "Hard",
    tags: ["Hash Table", "String", "Backtracking", "Breadth-First Search"],
    leetcode_id: "126",
  },
  {
    id: 127,
    title: "Word Ladder",
    difficulty: "Hard",
    tags: ["Hash Table", "String", "Breadth-First Search"],
    leetcode_id: "127",
  },
  {
    id: 128,
    title: "Longest Consecutive Sequence",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "Union Find"],
    leetcode_id: "128",
  },
  {
    id: 129,
    title: "Sum Root to Leaf Numbers",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "129",
  },
  {
    id: 130,
    title: "Surrounded Regions",
    difficulty: "Medium",
    tags: [
      "Array",
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Matrix",
    ],
    leetcode_id: "130",
  },
  {
    id: 131,
    title: "Palindrome Partitioning",
    difficulty: "Medium",
    tags: ["String", "Dynamic Programming", "Backtracking"],
    leetcode_id: "131",
  },
  {
    id: 132,
    title: "Palindrome Partitioning II",
    difficulty: "Hard",
    tags: ["String", "Dynamic Programming"],
    leetcode_id: "132",
  },
  {
    id: 133,
    title: "Clone Graph",
    difficulty: "Medium",
    tags: ["Hash Table", "Depth-First Search", "Breadth-First Search", "Graph"],
    leetcode_id: "133",
  },
  {
    id: 134,
    title: "Gas Station",
    difficulty: "Medium",
    tags: ["Array", "Greedy"],
    leetcode_id: "134",
  },
  {
    id: 135,
    title: "Candy",
    difficulty: "Hard",
    tags: ["Array", "Greedy"],
    leetcode_id: "135",
  },
  {
    id: 136,
    title: "Single Number",
    difficulty: "Easy",
    tags: ["Array", "Bit Manipulation"],
    leetcode_id: "136",
  },
  {
    id: 137,
    title: "Single Number II",
    difficulty: "Medium",
    tags: ["Array", "Bit Manipulation"],
    leetcode_id: "137",
  },
  {
    id: 138,
    title: "Copy List with Random Pointer",
    difficulty: "Medium",
    tags: ["Hash Table", "Linked List"],
    leetcode_id: "138",
  },
  {
    id: 139,
    title: "Word Break",
    difficulty: "Medium",
    tags: [
      "Hash Table",
      "String",
      "Dynamic Programming",
      "Trie",
      "Memoization",
    ],
    leetcode_id: "139",
  },
  {
    id: 140,
    title: "Word Break II",
    difficulty: "Hard",
    tags: [
      "Hash Table",
      "String",
      "Dynamic Programming",
      "Backtracking",
      "Trie",
      "Memoization",
    ],
    leetcode_id: "140",
  },
  {
    id: 141,
    title: "Linked List Cycle",
    difficulty: "Easy",
    tags: ["Hash Table", "Linked List", "Two Pointers"],
    leetcode_id: "141",
  },
  {
    id: 142,
    title: "Linked List Cycle II",
    difficulty: "Medium",
    tags: ["Hash Table", "Linked List", "Two Pointers"],
    leetcode_id: "142",
  },
  {
    id: 143,
    title: "Reorder List",
    difficulty: "Medium",
    tags: ["Linked List", "Two Pointers", "Stack", "Recursion"],
    leetcode_id: "143",
  },
  {
    id: 144,
    title: "Binary Tree Preorder Traversal",
    difficulty: "Easy",
    tags: ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "144",
  },
  {
    id: 145,
    title: "Binary Tree Postorder Traversal",
    difficulty: "Easy",
    tags: ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "145",
  },
  {
    id: 146,
    title: "LRU Cache",
    difficulty: "Medium",
    tags: ["Hash Table", "Linked List", "Design", "Doubly-Linked List"],
    leetcode_id: "146",
  },
  {
    id: 147,
    title: "Insertion Sort List",
    difficulty: "Medium",
    tags: ["Linked List", "Sorting"],
    leetcode_id: "147",
  },
  {
    id: 148,
    title: "Sort List",
    difficulty: "Medium",
    tags: [
      "Linked List",
      "Two Pointers",
      "Divide and Conquer",
      "Sorting",
      "Merge Sort",
    ],
    leetcode_id: "148",
  },
  {
    id: 149,
    title: "Max Points on a Line",
    difficulty: "Hard",
    tags: ["Array", "Hash Table", "Math", "Geometry"],
    leetcode_id: "149",
  },
  {
    id: 150,
    title: "Evaluate Reverse Polish Notation",
    difficulty: "Medium",
    tags: ["Array", "Math", "Stack"],
    leetcode_id: "150",
  },
];
