import { Question } from "./api";

export const leetcodeQuestions: Question[] = [
  {
    id: 1,
    title: "Two Sum",
    difficulty: "Easy",
    tags: ["Array", "Hash Table"],
    leetcode_id: "1",
  },
  {
    id: 3,
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    tags: ["Hash Table", "String", "Sliding Window"],
    leetcode_id: "3",
  },
  {
    id: 11,
    title: "Container With Most Water",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Greedy"],
    leetcode_id: "11",
  },
  {
    id: 15,
    title: "3Sum",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Sorting"],
    leetcode_id: "15",
  },
  {
    id: 19,
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    tags: ["Linked List", "Two Pointers"],
    leetcode_id: "19",
  },
  {
    id: 20,
    title: "Valid Parentheses",
    difficulty: "Easy",
    tags: ["String", "Stack"],
    leetcode_id: "20",
  },
  {
    id: 21,
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    tags: ["Linked List", "Recursion"],
    leetcode_id: "21",
  },
  {
    id: 33,
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    tags: ["Array", "Binary Search"],
    leetcode_id: "33",
  },
  {
    id: 36,
    title: "Valid Sudoku",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "Matrix"],
    leetcode_id: "36",
  },
  {
    id: 49,
    title: "Group Anagrams",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "String", "Sorting"],
    leetcode_id: "49",
  },
  {
    id: 98,
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    leetcode_id: "98",
  },
  {
    id: 100,
    title: "Same Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "100",
  },
  {
    id: 102,
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    tags: ["Tree", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "102",
  },
  {
    id: 104,
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "104",
  },
  {
    id: 110,
    title: "Balanced Binary Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "110",
  },
  {
    id: 121,
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    tags: ["Array", "Dynamic Programming"],
    leetcode_id: "121",
  },
  {
    id: 125,
    title: "Valid Palindrome",
    difficulty: "Easy",
    tags: ["Two Pointers", "String"],
    leetcode_id: "125",
  },
  {
    id: 128,
    title: "Longest Consecutive Sequence",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "Union Find"],
    leetcode_id: "128",
  },
  {
    id: 130,
    title: "Surrounded Regions",
    difficulty: "Medium",
    tags: [
      "Array",
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Matrix",
    ],
    leetcode_id: "130",
  },
  {
    id: 133,
    title: "Clone Graph",
    difficulty: "Medium",
    tags: ["Hash Table", "Depth-First Search", "Breadth-First Search", "Graph"],
    leetcode_id: "133",
  },
  {
    id: 141,
    title: "Linked List Cycle",
    difficulty: "Easy",
    tags: ["Hash Table", "Linked List", "Two Pointers"],
    leetcode_id: "141",
  },
  {
    id: 143,
    title: "Reorder List",
    difficulty: "Medium",
    tags: ["Linked List", "Two Pointers", "Stack", "Recursion"],
    leetcode_id: "143",
  },
  {
    id: 146,
    title: "LRU Cache",
    difficulty: "Medium",
    tags: ["Hash Table", "Linked List", "Design", "Doubly-Linked List"],
    leetcode_id: "146",
  },
  {
    id: 153,
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    tags: ["Array", "Binary Search"],
    leetcode_id: "153",
  },
  {
    id: 155,
    title: "Min Stack",
    difficulty: "Medium",
    tags: ["Stack", "Design"],
    leetcode_id: "155",
  },
  {
    id: 167,
    title: "Two Sum II - Input Array Is Sorted",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Binary Search"],
    leetcode_id: "167",
  },
  {
    id: 199,
    title: "Binary Tree Right Side View",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "199",
  },
  {
    id: 200,
    title: "Number of Islands",
    difficulty: "Medium",
    tags: [
      "Array",
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Matrix",
    ],
    leetcode_id: "200",
  },
  {
    id: 206,
    title: "Reverse Linked List",
    difficulty: "Easy",
    tags: ["Linked List", "Recursion"],
    leetcode_id: "206",
  },
  {
    id: 207,
    title: "Course Schedule",
    difficulty: "Medium",
    tags: [
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort",
    ],
    leetcode_id: "207",
  },
  {
    id: 210,
    title: "Course Schedule II",
    difficulty: "Medium",
    tags: [
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort",
    ],
    leetcode_id: "210",
  },
  {
    id: 215,
    title: "Kth Largest Element in an Array",
    difficulty: "Medium",
    tags: [
      "Array",
      "Divide and Conquer",
      "Sorting",
      "Heap (Priority Queue)",
      "Quickselect",
    ],
    leetcode_id: "215",
  },
  {
    id: 217,
    title: "Contains Duplicate",
    difficulty: "Easy",
    tags: ["Array", "Hash Table", "Sorting"],
    leetcode_id: "217",
  },
  {
    id: 226,
    title: "Invert Binary Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "226",
  },
  {
    id: 230,
    title: "Kth Smallest Element in a BST",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    leetcode_id: "230",
  },
  {
    id: 236,
    title: "Lowest Common Ancestor of a Binary Tree",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "236",
  },
  {
    id: 238,
    title: "Product of Array Except Self",
    difficulty: "Medium",
    tags: ["Array", "Prefix Sum"],
    leetcode_id: "238",
  },
  {
    id: 242,
    title: "Valid Anagram",
    difficulty: "Easy",
    tags: ["Hash Table", "String", "Sorting"],
    leetcode_id: "242",
  },
  {
    id: 347,
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    tags: [
      "Array",
      "Hash Table",
      "Divide and Conquer",
      "Sorting",
      "Heap (Priority Queue)",
      "Bucket Sort",
      "Counting",
      "Quickselect",
    ],
    leetcode_id: "347",
  },
  {
    id: 417,
    title: "Pacific Atlantic Water Flow",
    difficulty: "Medium",
    tags: ["Array", "Depth-First Search", "Breadth-First Search", "Matrix"],
    leetcode_id: "417",
  },
  {
    id: 424,
    title: "Longest Repeating Character Replacement",
    difficulty: "Medium",
    tags: ["Hash Table", "String", "Sliding Window"],
    leetcode_id: "424",
  },
  {
    id: 543,
    title: "Diameter of Binary Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "543",
  },
  {
    id: 572,
    title: "Subtree of Another Tree",
    difficulty: "Easy",
    tags: [
      "Tree",
      "Depth-First Search",
      "String Matching",
      "Binary Tree",
      "Hash Function",
    ],
    leetcode_id: "572",
  },
  {
    id: 695,
    title: "Max Area of Island",
    difficulty: "Medium",
    tags: [
      "Array",
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Matrix",
    ],
    leetcode_id: "695",
  },
  {
    id: 703,
    title: "Kth Largest Element in a Stream",
    difficulty: "Easy",
    tags: [
      "Tree",
      "Design",
      "Binary Search Tree",
      "Heap (Priority Queue)",
      "Binary Tree",
      "Data Stream",
    ],
    leetcode_id: "703",
  },
  {
    id: 704,
    title: "Binary Search",
    difficulty: "Easy",
    tags: ["Array", "Binary Search"],
    leetcode_id: "704",
  },
  {
    id: 739,
    title: "Daily Temperatures",
    difficulty: "Medium",
    tags: ["Array", "Stack", "Monotonic Stack"],
    leetcode_id: "739",
  },
  {
    id: 1046,
    title: "Last Stone Weight",
    difficulty: "Easy",
    tags: ["Array", "Heap (Priority Queue)"],
    leetcode_id: "1046",
  },
  {
    id: 1448,
    title: "Count Good Nodes in Binary Tree",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "1448",
  },
];
