import { Question } from "./api";

export const leetcodeQuestions: Question[] = [
  {
    id: 1,
    title: "Two Sum",
    difficulty: "Easy",
    tags: ["Array", "Hash Table"],
    leetcode_id: "1",
    url: "https://leetcode.com/problems/two-sum/",
  },
  {
    id: 3,
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    tags: ["Hash Table", "String", "Sliding Window"],
    leetcode_id: "3",
    url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
  },
  {
    id: 11,
    title: "Container With Most Water",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Greedy"],
    leetcode_id: "11",
    url: "https://leetcode.com/problems/container-with-most-water/",
  },
  {
    id: 15,
    title: "3Sum",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Sorting"],
    leetcode_id: "15",
    url: "https://leetcode.com/problems/3sum/",
  },
  {
    id: 19,
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    tags: ["Linked List", "Two Pointers"],
    leetcode_id: "19",
    url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
  },
  {
    id: 20,
    title: "Valid Parentheses",
    difficulty: "Easy",
    tags: ["String", "Stack"],
    leetcode_id: "20",
    url: "https://leetcode.com/problems/valid-parentheses/",
  },
  {
    id: 21,
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    tags: ["Linked List", "Recursion"],
    leetcode_id: "21",
    url: "https://leetcode.com/problems/merge-two-sorted-lists/",
  },
  {
    id: 33,
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    tags: ["Array", "Binary Search"],
    leetcode_id: "33",
    url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
  },
  {
    id: 36,
    title: "Valid Sudoku",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "Matrix"],
    leetcode_id: "36",
    url: "https://leetcode.com/problems/valid-sudoku/",
  },
  {
    id: 49,
    title: "Group Anagrams",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "String", "Sorting"],
    leetcode_id: "49",
    url: "https://leetcode.com/problems/group-anagrams/",
  },
  {
    id: 98,
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    leetcode_id: "98",
    url: "https://leetcode.com/problems/validate-binary-search-tree/",
  },
  {
    id: 100,
    title: "Same Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "100",
    url: "https://leetcode.com/problems/same-tree/",
  },
  {
    id: 102,
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    tags: ["Tree", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "102",
    url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
  },
  {
    id: 104,
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "104",
    url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
  },
  {
    id: 110,
    title: "Balanced Binary Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "110",
    url: "https://leetcode.com/problems/balanced-binary-tree/",
  },
  {
    id: 121,
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    tags: ["Array", "Dynamic Programming"],
    leetcode_id: "121",
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
  },
  {
    id: 125,
    title: "Valid Palindrome",
    difficulty: "Easy",
    tags: ["Two Pointers", "String"],
    leetcode_id: "125",
    url: "https://leetcode.com/problems/valid-palindrome/",
  },
  {
    id: 128,
    title: "Longest Consecutive Sequence",
    difficulty: "Medium",
    tags: ["Array", "Hash Table", "Union Find"],
    leetcode_id: "128",
    url: "https://leetcode.com/problems/longest-consecutive-sequence/",
  },
  {
    id: 130,
    title: "Surrounded Regions",
    difficulty: "Medium",
    tags: [
      "Array",
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Matrix",
    ],
    leetcode_id: "130",
    url: "https://leetcode.com/problems/surrounded-regions/",
  },
  {
    id: 133,
    title: "Clone Graph",
    difficulty: "Medium",
    tags: ["Hash Table", "Depth-First Search", "Breadth-First Search", "Graph"],
    leetcode_id: "133",
    url: "https://leetcode.com/problems/clone-graph/",
  },
  {
    id: 141,
    title: "Linked List Cycle",
    difficulty: "Easy",
    tags: ["Hash Table", "Linked List", "Two Pointers"],
    leetcode_id: "141",
    url: "https://leetcode.com/problems/linked-list-cycle/",
  },
  {
    id: 143,
    title: "Reorder List",
    difficulty: "Medium",
    tags: ["Linked List", "Two Pointers", "Stack", "Recursion"],
    leetcode_id: "143",
    url: "https://leetcode.com/problems/reorder-list/",
  },
  {
    id: 146,
    title: "LRU Cache",
    difficulty: "Medium",
    tags: ["Hash Table", "Linked List", "Design", "Doubly-Linked List"],
    leetcode_id: "146",
    url: "https://leetcode.com/problems/lru-cache/",
  },
  {
    id: 153,
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    tags: ["Array", "Binary Search"],
    leetcode_id: "153",
    url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
  },
  {
    id: 155,
    title: "Min Stack",
    difficulty: "Medium",
    tags: ["Stack", "Design"],
    leetcode_id: "155",
    url: "https://leetcode.com/problems/min-stack/",
  },
  {
    id: 167,
    title: "Two Sum II - Input Array Is Sorted",
    difficulty: "Medium",
    tags: ["Array", "Two Pointers", "Binary Search"],
    leetcode_id: "167",
    url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
  },
  {
    id: 199,
    title: "Binary Tree Right Side View",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "199",
    url: "https://leetcode.com/problems/binary-tree-right-side-view/",
  },
  {
    id: 200,
    title: "Number of Islands",
    difficulty: "Medium",
    tags: [
      "Array",
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Matrix",
    ],
    leetcode_id: "200",
    url: "https://leetcode.com/problems/number-of-islands/",
  },
  {
    id: 206,
    title: "Reverse Linked List",
    difficulty: "Easy",
    tags: ["Linked List", "Recursion"],
    leetcode_id: "206",
    url: "https://leetcode.com/problems/reverse-linked-list/",
  },
  {
    id: 207,
    title: "Course Schedule",
    difficulty: "Medium",
    tags: [
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort",
    ],
    leetcode_id: "207",
    url: "https://leetcode.com/problems/course-schedule/",
  },
  {
    id: 210,
    title: "Course Schedule II",
    difficulty: "Medium",
    tags: [
      "Depth-First Search",
      "Breadth-First Search",
      "Graph",
      "Topological Sort",
    ],
    leetcode_id: "210",
    url: "https://leetcode.com/problems/course-schedule-ii/",
  },
  {
    id: 215,
    title: "Kth Largest Element in an Array",
    difficulty: "Medium",
    tags: [
      "Array",
      "Divide and Conquer",
      "Sorting",
      "Heap (Priority Queue)",
      "Quickselect",
    ],
    leetcode_id: "215",
    url: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
  },
  {
    id: 217,
    title: "Contains Duplicate",
    difficulty: "Easy",
    tags: ["Array", "Hash Table", "Sorting"],
    leetcode_id: "217",
    url: "https://leetcode.com/problems/contains-duplicate/",
  },
  {
    id: 226,
    title: "Invert Binary Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "226",
    url: "https://leetcode.com/problems/invert-binary-tree/",
  },
  {
    id: 230,
    title: "Kth Smallest Element in a BST",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
    leetcode_id: "230",
    url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
  },
  {
    id: 236,
    title: "Lowest Common Ancestor of a Binary Tree",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "236",
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
  },
  {
    id: 238,
    title: "Product of Array Except Self",
    difficulty: "Medium",
    tags: ["Array", "Prefix Sum"],
    leetcode_id: "238",
    url: "https://leetcode.com/problems/product-of-array-except-self/",
  },
  {
    id: 242,
    title: "Valid Anagram",
    difficulty: "Easy",
    tags: ["Hash Table", "String", "Sorting"],
    leetcode_id: "242",
    url: "https://leetcode.com/problems/valid-anagram/",
  },
  {
    id: 347,
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    tags: [
      "Array",
      "Hash Table",
      "Divide and Conquer",
      "Sorting",
      "Heap (Priority Queue)",
      "Bucket Sort",
      "Counting",
      "Quickselect",
    ],
    leetcode_id: "347",
    url: "https://leetcode.com/problems/top-k-frequent-elements/",
  },
  {
    id: 417,
    title: "Pacific Atlantic Water Flow",
    difficulty: "Medium",
    tags: ["Array", "Depth-First Search", "Breadth-First Search", "Matrix"],
    leetcode_id: "417",
    url: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
  },
  {
    id: 424,
    title: "Longest Repeating Character Replacement",
    difficulty: "Medium",
    tags: ["Hash Table", "String", "Sliding Window"],
    leetcode_id: "424",
    url: "https://leetcode.com/problems/longest-repeating-character-replacement/",
  },
  {
    id: 543,
    title: "Diameter of Binary Tree",
    difficulty: "Easy",
    tags: ["Tree", "Depth-First Search", "Binary Tree"],
    leetcode_id: "543",
    url: "https://leetcode.com/problems/diameter-of-binary-tree/",
  },
  {
    id: 572,
    title: "Subtree of Another Tree",
    difficulty: "Easy",
    tags: [
      "Tree",
      "Depth-First Search",
      "String Matching",
      "Binary Tree",
      "Hash Function",
    ],
    leetcode_id: "572",
    url: "https://leetcode.com/problems/subtree-of-another-tree/",
  },
  {
    id: 695,
    title: "Max Area of Island",
    difficulty: "Medium",
    tags: [
      "Array",
      "Depth-First Search",
      "Breadth-First Search",
      "Union Find",
      "Matrix",
    ],
    leetcode_id: "695",
    url: "https://leetcode.com/problems/max-area-of-island/",
  },
  {
    id: 703,
    title: "Kth Largest Element in a Stream",
    difficulty: "Easy",
    tags: [
      "Tree",
      "Design",
      "Binary Search Tree",
      "Heap (Priority Queue)",
      "Binary Tree",
      "Data Stream",
    ],
    leetcode_id: "703",
    url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
  },
  {
    id: 704,
    title: "Binary Search",
    difficulty: "Easy",
    tags: ["Array", "Binary Search"],
    leetcode_id: "704",
    url: "https://leetcode.com/problems/binary-search/",
  },
  {
    id: 739,
    title: "Daily Temperatures",
    difficulty: "Medium",
    tags: ["Array", "Stack", "Monotonic Stack"],
    leetcode_id: "739",
    url: "https://leetcode.com/problems/daily-temperatures/",
  },
  {
    id: 1046,
    title: "Last Stone Weight",
    difficulty: "Easy",
    tags: ["Array", "Heap (Priority Queue)"],
    leetcode_id: "1046",
    url: "https://leetcode.com/problems/last-stone-weight/",
  },
  {
    id: 1448,
    title: "Count Good Nodes in Binary Tree",
    difficulty: "Medium",
    tags: ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
    leetcode_id: "1448",
    url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
  },
];
